breqwatr/voithos

docs/_config.yml

Simple title change to mach our other sites ... VDI & Cloud

Title Change

---

test/cli/service/test_arcus_api.py
voithos/cli/service/arcus/client.py
voithos/lib/service/arcus/api.py
voithos/lib/service/arcus/client.py

This PR address #621 and enables host network on arcus api and client containers. We were doing port forwarding previously, which was doing some weird stuff with traffic comming from ext-net to ext vip in arcus client.
@kylep It also includes some of the changes you made.

Breq 621 voithos changes for ports

---

docs/ceph-install.md
docs/grafana-prometheus-config.md
docs/openstack-ceph.md
docs/openstack-kolla-bootstrap.md
docs/openstack-kolla-deploy.md
docs/openstack-kolla-pull.md
docs/openstack-registry-mirror.md
docs/openstack-with-ceph.md
setup.py

This PR addresses #669 and some other doc issue discussed earlier.

Breq 669 voithos doc

---

voithos/lib/files/grafana/node_config.json

[Breq 734] Grafana units change

---

docs/offline-openstack-with-iscsi.md
docs/openstack-gnocchi-config.md
docs/openstack-kolla-config.md
docs/openstack-kolla-globals.md
docs/openstack-with-ceph.md
docs/openstack-with-lvm.md

[Breq 868] Gnocchi Ceilometer Voithos Doc

---

docs/openstack-kolla-config.md

[Breq 988] Neutron Search Domain

---

voithos/lib/service/arcus/api.py

This PR addresses #1057. Now database-init command not only check arcus db and user but also arcus user privileges.

[BREQ 1057] Give db access to existing arcus user

---

docs/openstack-kolla-globals.md
docs/prometheus-flags.md

[BREQ 1054] Prometheus CLI Flags Doc

---

docs/openstack-kolla-config.md

[BREQ 953] Disable ephemeral disk usage

---

docs/kibana-setup.md
docs/offline-openstack-with-iscsi.md
docs/openstack-kolla-config.md
docs/openstack-kolla-globals.md
docs/openstack-with-ceph.md
docs/openstack-with-lvm.md

This PR addresses #1069. Some changes in relevant [confluence](https://breqwatr-arcus.atlassian.net/wiki/spaces/OD/pages/1016561677/Elasticsearch+Kibana) doc are also part of this Ticket.

[Breq 1069] Central logging voithos docs

---

voithos/cli/service/rsyslog.py
voithos/cli/service/service.py
voithos/lib/service/rsyslog.py

This PR address #1119. By merging this PR, we shall have rsyslog support in voithos.

[Breq 1119] Syslog Support Voithos Cli

---

docs/index.md
docs/syslog-install.md

[BREQ 1123] Syslog Voithos Docs

---

docs/openstack-kolla-globals.md

Added "enable_neutron_provider_networks: yes" under Neutron section

Added "enable_neutron_provider_networks: yes" under Neutron section

---

powershell/voithos.psm1

Added "w10" to the validation distro options

BREQ-1205-Add-w10-to-VirtioDrivers-command

---

docs/arcus-install.md
docs/ceph-pools.md
docs/index.md
docs/offline-deployment-server.md
docs/openstack-with-ceph.md
voithos/cli/service/apt.py
voithos/cli/service/pip.py
voithos/constants.py
voithos/lib/service/apt.py
voithos/lib/service/pip.py

This PR addresses #1218. It adds voithos docs for offline install along with some minor changes.

[BREQ 1218] Voithos docs for offline install

---

docs/migrations/rhel-conversion.md
voithos/cli/migrate/rhel.py
voithos/lib/migrate/rhel.py
voithos/lib/system.py

This rewrite of the RHEL migrate code will

Breq 1185 rhel mounts

---

docs/index.md
docs/offline-deployment-server.md
docs/openstack-server-setup.md

[BREQ 1128] time zone voithos docs

---

README.md
voithos/cli/util/util.py
voithos/constants.py

This PR addresses #1239. After this PR is merged, S3 upload commands will only work in s3 dev mode.

[BREQ 1239] CLI S3 Dev Mode

---

docs/migrations/rhel-conversion.md
docs/migrations/ubuntu-conversion.md

1- Added the note to check and update if necessary the host file once the devices are mounted .   2 - The command to set the DHCP interface does not require to specify the <device>

BREQ-1291-Voithos-Voithos-AddCheckingHostname

---

docs/migrations/windows-conversion.md

updated documentation for windows migration run-once script for additional options related to the DeviceInstall service and to disable the firewall. Also updated comments to make the command names consistent.

BREQ-1311-Add-firewall-disable-and-service-steps-to-Voithos

---

powershell/voithos.psm1

Added the OfflineScanAndFix parameter

BREQ-1284-VoithosAdd-OfflineScanAndFix

---

docs/migrations/windows-conversion.md
powershell/voithos.psm1

Changed the path to Windows\System32\WindowsPowerShell\v1.0\Modules

BREQ-1313-VoithosAddChecktoMakeSureVoithosModuleDeployedRight

---

powershell/voithos.psm1

Prevent to create backups if there is an existing backup.

BREQ-1285-VoithosPreventOverwritingGPOBackups

---

docs/openstack-kolla-config.md
docs/openstack-server-setup.md

This PR addresses #1088 and #1347.

[Breq 1088 1347]

---

docs/openstack-kolla-pull.md

[Breq 1305] Voithos doc pull images command

---

voithos/lib/service/arcus/api.py

[Breq 717] Token Creation Failure Error Message

---

docs/arcus-install.md
docs/openstack-ceph.md
docs/openstack-cinder-unity.md
docs/openstack-with-ceph.md
docs/unity-setup.md

This PR addresses #1210 and #1358.

[Breq 1210][Breq 1358] voithos docs changes

---

docs/openstack-gnocchi-config.md
docs/openstack-kolla-config.md

[BREQ 1453] archive policy changes for ceilometer and gnocchi

---

docs/openstack-ceph.md
docs/openstack-kolla-globals.md

This PR addresses missing part of #1067.

[BREQ 1067] missing voithos docs gnocchi backend storage ceph

---

powershell/voithos.psm1

Detect ComputerName to make sure the VM is the target VM.

Added function to detect ComputerName

---

docs/openstack-kolla-globals.md

[BREQ 1855] Ceph configs globals file

---

voithos/cli/service/arcus/integrations.py
voithos/lib/service/arcus/integrations.py

This PR addresses #1863. After this PR is merged, links option can be passed at integration creation time instead of updating links after integration creation.

[BREQ 1863] Add links argument in integration create command

---

docs/openstack-kolla-globals.md

added comment to note requirement for field after Victoria release.

updated docs for ceph nova username requirement after Victoria release

---

docs/openstack-kolla-config.md

Updated voithos documentation in the nova config section.

BREQ-1889-FixVMResizeIssue-UpdatedVoithosDocs
